export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  TURNAROUND_NOT_FOUND: "TURNAROUND_NOT_FOUND",
  RELEASE_BLOCKED: "RELEASE_BLOCKED",
  RELEASE_ALREADY_DONE: "RELEASE_ALREADY_DONE",
  RELEASE_RACE_LOST: "RELEASE_RACE_LOST",
  TASK_NOT_FOUND: "TASK_NOT_FOUND",
  TASK_ALREADY_SIGNED: "TASK_ALREADY_SIGNED",
  BOOKING_NOT_FOUND: "BOOKING_NOT_FOUND",
  DELAY_NOT_FOUND: "DELAY_NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR"
} as const;
