export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  TURNAROUND_NOT_FOUND: "TURNAROUND_NOT_FOUND",
  TURNAROUND_ALREADY_RELEASED: "TURNAROUND_ALREADY_RELEASED",
  RELEASE_BLOCKED: "RELEASE_BLOCKED",
  CONCURRENT_RELEASE: "CONCURRENT_RELEASE"
} as const;
